---
title: "BADT26"
---

# First meeting 2-3 Feb

**Day 1 Monday, 2 Feb 2026 (12-16)**

Lundmarkssalen Astronomihuset

[Course introduction](pages\course_intro.qmd)

Lecture with non-computer exercises: [Bayesian inference and subjective probability](pages\Bayesian_inference_subjective_probability.qmd)

Reading: BR* (Chapters 1 and 2) and DBDA* (Chapter 2, 4 and 5)

[Exercise 1: Probability](pages\exercise_1.qmd)

Lecture about [conjugate models](pages\conjugate_models.qmd)

Readings: BR* (Chapters 3 and 5) and DBDA* (Chapters 6)

[Exercise 2: Conjugate models](pages\exercise_2.qmd)

Lecture on [Bayesian analysis using MCMC](pages\MCMC.qmd)

[Exercise 3. Write your own MCMC sampler](pages\exercise_3.qmd) 

**Day 2 Tuesday, 3 Feb 09.00 - 14.00**

Pufendorf Institute for Advanced Studies

9.15 Bayesian analysis using MCMC

Reading: BR* (Chapters 6, 7, 8) and DBDA* (Chapter 7)

[Exercise 2: Conjugate models](pages\exercise_2.qmd)
[Solution](pages\solution_exercise_2.qmd)

[Exercise 3. Write your own MCMC sampler](pages\exercise_3.qmd)

Short lecture [Introduction to software for MCMC sampling](pages\MCMC.qmd)

Short lecture [Predictive performance in Bayesian inference](pages\PP.qmd)

[Exercise 4. Get started with a software for MCMC sampling](pages\exercise_4.qmd)

12-13 Lunch

Lecture [Generalised Linear Regression models](pages\Bayesian_GLM.qmd)

Reading: BR* (Chapters 9, 10, 11) and DBDA* (Chapter 15)

14.15 Almost a lecture on [Decision theory](pages/decision_theory.qmd)

Reading: 1* and 2*

# Second meeting 24-25 Feb

**Tuesday, 24 Feb 2026 (12-16) Världen Geocentrum I** 

12.15 Lecture Decision making under uncertainty

13.15 Case studies on Bayesian data and decision analysis

BR* (Chapters 11, 13-17) and DBDA* (Chapter 9 and 10) 

14.45 Coffee

15.00 Preparation Literature seminar

16.00 End of day

**Wednesday, 25 Feb 2026 (9-15)**

09.15 Case studies on Bayesian data and decision analysis

11.30 Literature seminar theme 1

12.00 Lunch

13.15 Literature seminar theme 2

13.45 Coffee

14.00 Literature seminar theme 3

14.30 Pitching individual project

15.00 End of day


